# Generated by Django 5.0.3 on 2024-06-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_remove_news_created_at_news_dislikes_news_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
    ]
